### PR TITLE
Add OS specific commands for kindlegen

### PR DESCRIPTION
**Pull request by aakashjog**

### CODE REVIEW

**Comment by ofalvai** [comment]
Thanks for the pull request! Can you change your code to use `subprocess.call` in both cases? The [os.system documentation](https://docs.python.org/3.6/library/os.html#os.system) says `subprocess.call` is the preferred way. Also, in your code stdout is not redirected to the log file.

**Comment by aakashjog** [comment]
Done!

**Comment by ofalvai** [comment]
Thank you for your contribution, I've merged this into master.

**Comment by aakashjog** [comment]
Great, happy to help! 😄

**Pull request merged**
